export const sessions = {
  "VSLA Methodology": "XQ3eQax0uIk",
  "VSLA TOT": "qEium1Lrsc0",
  "VSLA Saving and Borrowing": "ZOAmd05j2t9",
  "Financial Literacy": "LUR9gZUkcrr",
  "SPM Training": "EYMKGdEeniO",
  "Bank Linkages": "gmEcQwHbivM",
  SINOVUYO: "ptI9Geufl7R",
  "MOE Journeys Plus": "HkuYbbefaEM",
  "MOH Journeys curriculum": "P4tTIlhX1yB",
  "No means No sessions (Boys)": "WuPXlmvSfVJ",
  "No means No sessions (Boys) New Curriculum": "TIObJloCVdC",
  "No means No sessions (Girls)": "okgcyLQNVFe",
  ECD: "QHaULS891IF",
};
